#!/usr/bin/env node

"use strict";

var app = require('express')(),
    express = require('express'),
    server = require('http').createServer(app),
    io = require('socket.io').listen(server),
    listening = [],
    fs = require('fs'),
    when = require('when'),
    sequence = require('sequence'),
    audioFiles = {};

server.listen(80);
app.use("/images", express.static(__dirname + "/images"));
app.use("/static", express.static(__dirname + "/static"));

app.get('/', function (req, res) {
  var ua = req.header('user-agent');
  if (/mobile/i.test(ua)) {
      return res.sendfile(__dirname + '/slave_mobile.html');
  }
  return res.sendfile(__dirname + '/slave.html');
});

app.get('/master', function(req, res) {
    res.sendfile(__dirname + '/master.html');
});

addFiles().then(function(files){
    audioFiles = files;
    console.log(audioFiles);
    io.sockets.on('connection', function (socket) {

        socket.on('masterEvent', function (data) {
            if (data.audioEvent === 'requestClientList') {
                var htmlString = buildClientsList();
                socket.emit('masterEvent', { 
                    'audioEvent': 'updateSources',
                    'sources': htmlString
                }); 
            }
            else if (data.audioEvent === 'reload') {
                addFiles().then(function(files){
                    audioFiles = files;
                    var htmlString = buildClientsList();
                    socket.broadcast.emit('slaveEvent', data); 
                    socket.emit('masterEvent', { 
                        'audioEvent': 'updateSources',
                        'sources': htmlString
                    }); 
                })
            }
            else if (data.audioEvent === 'reload') {
                addFiles().then(function(files){
                    audioFiles = files;
                    var htmlString = buildClientsList();
                    socket.broadcast.emit('slaveEvent', data); 
                    socket.emit('masterEvent', { 
                        'audioEvent': 'updateSources',
                        'sources': htmlString
                    }); 
                })
            }
            else {
                socket.broadcast.emit('slaveEvent', data);
            }
        });

        socket.on('slaveEvent', function (data){
            console.log(data);
            if (data.audioEvent === 'loaded') {
                audioFiles[data.source] = audioFiles[data.source] + 1;
                var htmlString = buildClientsList();
                socket.broadcast.emit('masterEvent', { 
                    'audioEvent': 'updateSources',
                    'sources': htmlString
                }); 
            }
            else if (data.audioEvent === 'removeSource') {
                audioFiles[data.source] = audioFiles[data.source] - 1;
                var htmlString = buildClientsList();
                socket.broadcast.emit('masterEvent', { 
                    'audioEvent': 'updateSources',
                    'sources': htmlString
                }); 
            }
            else if (data.audioEvent == 'requestSource') {
                var nextFile = getNextAudioFile();
                console.log(nextFile);
                if (nextFile){
                    
                    socket.emit('slaveEvent', { 
                        'audioEvent': 'load',
                        'source': nextFile
                    });  
                    
                }
                else {
                    nextFile = getRandomAudioFile();
                    socket.emit('slaveEvent', { 
                        'audioEvent': 'load',
                        'source': nextFile
                    }); 

                    // console.log('we all full up');
                    // socket.emit('slaveEvent', { 
                    //     'audioEvent': 'error',
                    //     'message': 'full'
                    // });
                }
            }
        });
    });
});

function addFiles(){
    var d = when.defer(),
        filesMap = {};
    fs.readdir(__dirname + '/static/audio', function(err, files){
        if (!err){
            files.forEach(function(file){
                filesMap[file] = 0;
            });
            d.resolve(filesMap);
        }
    });
    return d.promise;
}

function getNextAudioFile(){
    for (var file in audioFiles){
        if (audioFiles[file] === 0) {
            return file;
        }
    }
    return false;
}

function getRandomAudioFile() {
    var result,
        count = 0,
        file;
    for (file in audioFiles)
        if (Math.random() < 1/++count)
           result = file;
    return result;
}

function buildClientsList(){
    var htmlString = '',
        file;
    for (file in audioFiles) {
        if (audioFiles[file]) {
            htmlString = htmlString + '<br/>' + file + ' (' + audioFiles[file] + ')';
        }
    }
    return htmlString;
}